import Image01 from '!url-loader!~/assets/img/animation/image05.png'
import { ISponsor, Rank } from '../types/sponsors'

export const sponsorSupportLevelTitle = (rank: Rank) => {
  switch (rank) {
  case 'platinum':
    return 'Platinum'
  case 'gold':
    return 'Gold'
  case 'silver':
    return 'Silver'
  case 'bronze':
    return 'Bronze'
  case 'media':
    return 'Media'
  case 'specialMedia':
    return 'Special Media'
  case 'broadcaster':
    return '配信'
  default:
    const _missing: never = rank
    return ''
  }
}

export const sponsors: ISponsor[] = [
  {
    id: '1234',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'platinum',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '2345',
    name_jp: 'Sponsor_2',
    name_jp_kana: 'スポンサー_2',
    name_en: 'Sponsor_2',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'platinum',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345634',
    name_jp: 'Sponsor_3',
    name_jp_kana: 'スポンサー_3',
    name_en: 'Sponsor_3',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'platinum',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  // Gold Sponsor
  {
    id: '1234',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '2345',
    name_jp: 'Sponsor_2',
    name_jp_kana: 'スポンサー_2',
    name_en: 'Sponsor_2',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345634',
    name_jp: 'Sponsor_3',
    name_jp_kana: 'スポンサー_3',
    name_en: 'Sponsor_3',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345123',
    name_jp: 'Sponsor_4',
    name_jp_kana: 'スポンサー_4',
    name_en: 'Sponsor_4',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '123456789',
    name_jp: 'Sponsor_5',
    name_jp_kana: 'スポンサー_5',
    name_en: 'Sponsor_5',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_6',
    name_jp_kana: 'スポンサー_6',
    name_en: 'Sponsor_6',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: 'asdfasdfqwer',
    name_jp: 'Sponsor_3',
    name_jp_kana: 'スポンサー_3',
    name_en: 'Sponsor_3',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'gold',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  // Silver Sponsor

  {
    id: '1234',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '2345',
    name_jp: 'Sponsor_2',
    name_jp_kana: 'スポンサー_2',
    name_en: 'Sponsor_2',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345634',
    name_jp: 'Sponsor_3',
    name_jp_kana: 'スポンサー_3',
    name_en: 'Sponsor_3',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345123',
    name_jp: 'Sponsor_4',
    name_jp_kana: 'スポンサー_4',
    name_en: 'Sponsor_4',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '123456789',
    name_jp: 'Sponsor_5',
    name_jp_kana: 'スポンサー_5',
    name_en: 'Sponsor_5',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_6',
    name_jp_kana: 'スポンサー_6',
    name_en: 'Sponsor_6',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345634',
    name_jp: 'Sponsor_7',
    name_jp_kana: 'スポンサー_7',
    name_en: 'Sponsor_7',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '12345123',
    name_jp: 'Sponsor_8',
    name_jp_kana: 'スポンサー_8',
    name_en: 'Sponsor_48',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: '123456789',
    name_jp: 'Sponsor_9',
    name_jp_kana: 'スポンサー_9',
    name_en: 'Sponsor_9',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_10',
    name_jp_kana: 'スポンサー_10',
    name_en: 'Sponsor_10',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'silver',
    bio: '12円芸団にどー文川辺べぐ秋掲ス船真掛ー点大べぱ的25王74各2亭そぱわル。量ユツワヘ六31月ぽそや態時ぐぎ字込ヘレリ導治サス却季スレシ東視シヌウコ棋属で転流ヨイリ会同をぴてリ扱六ゃだ置圧キノ断候職表よのね。芸ク味込セニ殊歴マ図権びぞあも問浜されてべ並宿紀そずさゃ品身ロ見器よ言高メヤ時間結ほ口媛せげはふ圏気ネミエ読夜きえに間的べぶづ彦刊エヱオ城囲刊ヘタ転単純役ひへ。',
  },

  // Bronze Sponsor
  {
    id: '1234',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '2345',
    name_jp: 'Sponsor_2',
    name_jp_kana: 'スポンサー_2',
    name_en: 'Sponsor_2',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '12345634',
    name_jp: 'Sponsor_3',
    name_jp_kana: 'スポンサー_3',
    name_en: 'Sponsor_3',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '12345123',
    name_jp: 'Sponsor_4',
    name_jp_kana: 'スポンサー_4',
    name_en: 'Sponsor_4',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '123456789',
    name_jp: 'Sponsor_5',
    name_jp_kana: 'スポンサー_5',
    name_en: 'Sponsor_5',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_6',
    name_jp_kana: 'スポンサー_6',
    name_en: 'Sponsor_6',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  ,
  {
    id: '12345634',
    name_jp: 'Sponsor_7',
    name_jp_kana: 'スポンサー_7',
    name_en: 'Sponsor_7',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '12345123',
    name_jp: 'Sponsor_8',
    name_jp_kana: 'スポンサー_8',
    name_en: 'Sponsor_48',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: '123456789',
    name_jp: 'Sponsor_9',
    name_jp_kana: 'スポンサー_9',
    name_en: 'Sponsor_9',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_10',
    name_jp_kana: 'スポンサー_10',
    name_en: 'Sponsor_10',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_11',
    name_jp_kana: 'スポンサー_11',
    name_en: 'Sponsor_11',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'bronze',
  },

  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_11',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'specialMedia',
  },

  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'media',
  },
  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_2',
    name_jp_kana: 'スポンサー_2',
    name_en: 'Sponsor_2',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'media',
  },

  {
    id: 'asdfasdf',
    name_jp: 'Sponsor_1',
    name_jp_kana: 'スポンサー_1',
    name_en: 'Sponsor_1',
    twitter: '@vuefes',
    facebook: 'vuefes',
    image: Image01,
    corporate_url: '#',
    rank: 'broadcaster',
  },
]
