interface IStaff {
  name: string
  image?: string
  twitterID?: string
}

export const staffList: IStaff[] = [
  { name: 'tutti', image: 'tutti2612.jpeg', twitterID: 'tutti2612' },
  { name: '448jp', image: '448jp.png', twitterID: '448jp' },
  { name: 'grid', image: 'grid.jpeg', twitterID: '' },
  { name: 'happylifetaka', image: 'happylifetaka.png', twitterID: 'happylifetaka' },
  { name: 'hayashi171', image: 'hayashi171.jpeg', twitterID: '' },
  { name: 'jiyuujin', image: 'jiyuujin.png', twitterID: 'jiyuujinlab' },
  { name: 'kame', image: 'kame.jpeg', twitterID: 'dir20634' },
  { name: 'katuaki', image: '', twitterID: '' },
  { name: 'kazupon', image: 'kazupon.png', twitterID: 'kazu_pon' },
  { name: 'kazuyan', image: 'kazuyan.jpeg', twitterID: 'D_kazuyan' },
  { name: 'keita', image: 'keita.jpeg', twitterID: 'sdkk_tkks' },
  { name: 'kiaking', image: 'kiaking.jpeg', twitterID: 'kiaking' },
  { name: 'Kotaki', image: 'kotaki.jpeg', twitterID: 'j_jack01' },
  { name: 'maco', image: 'maco.jpeg', twitterID: 'maco_rasp' },
  { name: 'Masamita', image: 'masamita.jpeg', twitterID: '' },
  { name: 'Migii', image: 'migii.jpeg', twitterID: 'migii_1001' },
  { name: 'Miki Kuramata', image: '', twitterID: '' },
  { name: 'miyake', image: 'miyake.jpeg', twitterID: 'kazuyukimiyake' },
  { name: 'nal', image: 'nal.jpeg', twitterID: 'nal_pan' },
  { name: 'naokie', image: '', twitterID: '' },
  { name: 'Nozomu Ikuta', image: 'nozomu_ikuta.png', twitterID: 'NozomuIkuta' },
  { name: 'okakyo', image: 'okakyo.jpeg', twitterID: 'okakyo' },
  { name: 'rishihara', image: 'rishihara.jpeg', twitterID: '' },
  { name: 'robjam', image: 'robjam.png', twitterID: 'robjamdev' },
  { name: 'rry', image: 'rry.jpeg', twitterID: 'ryamakuchi' },
  { name: 'Rui Kiyoshima', image: '', twitterID: '' },
  { name: 'ryo_gk', image: 'ryo_gk.jpeg', twitterID: 'ryo_gk55' },
  { name: 'ryuhei373', image: 'ryuhei373.jpeg', twitterID: '373_3' },
  { name: 'Sanadi', image: 'sanadi.jpeg', twitterID: 'favorita_biz' },
  { name: 'sano', image: '', twitterID: '' },
  { name: 'shinji', image: '', twitterID: '' },
  { name: 'Shinya Ogawa', image: 'shinya_ogawa.jpeg', twitterID: 'DesignSupplyWeb' },
  { name: 'shiori', image: 'shiori.jpeg', twitterID: 'dummy11022' },
  { name: 'shiyuu', image: 'shiyuu.png', twitterID: 'shiyuu33' },
  { name: 'sugoikondo', image: '', twitterID: '' },
  { name: 'takuan', image: 'takuan.png', twitterID: 'takuan517' },
  { name: 'Tamiko Terasawa', image: '', twitterID: '' },
  { name: 'taz', image: '', twitterID: '' },
  { name: 'torish14', image: 'torish14.png', twitterID: 'torish14' },
  { name: 'wakamatsu', image: 'wakamatsu.jpeg', twitterID: 'hachi_ihcah' },
  { name: 'watasan', image: 'watasan.png', twitterID: 'hishiwata7' },
  { name: 'yaberah', image: '', twitterID: '' },
  { name: 'Yuhei FUJITA', image: 'yuhei_fujita.jpeg', twitterID: 'Yuhei_FUJITA' },
  { name: 'Yuuki Ishibashi', image: 'yuuki_ishibashi.jpeg', twitterID: 'Bassy3600' },
  { name: 'からころ', image: 'karacoro.jpeg', twitterID: 'karan_corons' },
  { name: 'さいかい', image: '', twitterID: '' },
  { name: 'すずき', image: '', twitterID: '' },
  { name: 'ちおにやん', image: '', twitterID: '' },
  { name: 'なかしま　じゅり', image: 'nakashima_38.jpeg', twitterID: 'nakashima_38' },
  { name: '平間久美子', image: 'kumin.png', twitterID: 'kumin' },
  { name: '米澤真衣', image: 'fuzno.jpeg', twitterID: 'fuzno' },
  { name: 'naramochi', image: 'naramochi.png', twitterID: '_naramochi' },
  { name: 'moabear', image: 'moabear.jpeg', twitterID: '' },
]
